# vim: tabstop=2:softtabstop=2:shiftwidth=2:expandtab

stages:
  - build
  - deploy

build_base_image:
  stage: build
  when: manual
  only:
    - master
  script:
    - docker login --username akhanbakhitov777 --password ${DOCKER_HUB_TOKEN}
    - ls
    - docker build -t akhanbakhitov777/oqustudy -f oqustudy.Dockerfile .
    - docker push akhanbakhitov777/oqustudy:latest
    - docker system prune -f

deploy:
  when: manual
  stage: deploy
  variables:
    SCREEN_NAME: "server"
    FROM_FOLDER: .
    TO_FOLDER: "/home/gitlab-runner/oppia"
  script:
    - docker login --username akhanbakhitov777 --password ${DOCKER_HUB_TOKEN}
    - docker pull akhanbakhitov777/oqustudy:latest
    - docker stop oqustudy || echo "oqustudy container is not running"
    - docker rm oqustudy || echo "oqustudy container is not exist"
    - docker run -d --name oqustudy -p 8181:80  -p 127.0.0.1:8000:8000 -v "/root/appengine.None.root/:/tmp" -v "${PWD}/../oppia:/oppia" akhanbakhitov777/oqustudy
    - docker system prune -f
    - docker volume prune -f
    - python3.6 waiting_up.py
